# Server Configuration
server.port=8081

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sr35285@gmail.com
spring.mail.password=yivdcofzswsspvnj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Application Configuration
spring.application.name=email-service

# Logging Configuration
logging.level.com.furnish.webapp.emailservice=DEBUG
logging.level.org.springframework.mail=DEBUG

# Thymeleaf Configuration
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false